automatically pick up linked node deps

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -2,44 +2,30 @@
 set -e
 
 indent() {
-    sed 's/^/      /'
+  sed 's/^/      /'
 }
 
-BUILD_DIR=$1
-ENV_DIR=$3
+BUILD_DIR=$(readlink -f $1)
 
-if [ ! -f ${ENV_DIR}/APP_DEPS ]; then
-    echo "APP_DEPS was not set. Aborting!" | indent
-    exit 1
-fi
-
-APP_DEPS=$(cat ${ENV_DIR}/APP_DEPS)       # ex. `api core`
-
+symlinks=$(find $BUILD_DIR/.heroku/node/lib/node_modules -maxdepth 1 -type l)
 (
-  for app_dir in ${APP_DEPS}; do
-    if [ -f ${app_dir}/package.json ]; then
-      cd $BUILD_DIR/$app_dir                                      &&
-      package_name_line=$(npm run env | grep "npm_package_name")  &&
-      package_name=$(cut -d "=" -f 2 <<< $package_name_line)
-
-      cd $BUILD_DIR                                               &&
-      touch "node_modules/$package_name"                          &&
-      rm "node_modules/$package_name"                                 # remove linked dependency
-
-      cd $BUILD_DIR/$app_dir                                      &&
-      echo 'pack'                                                 &&
-      pack=$(npm pack)                                                # pack dependency
-
-      cd $BUILD_DIR                                               &&
-      echo "npm install $pack"                                    &&
-      npm install $pack                                               # install dependency
-    fi
-  done
+for symlink in $symlinks; do
+  source=$(readlink -f $symlink)
+  if [[ $source/ = $BUILD_DIR/* ]]; then
+    echo "source $source"
+    app_source=$(echo $source | sed "s#$BUILD_DIR#/app#")
+    rm $symlink
+    echo "$symlink -> $app_source"
+    ln -s $app_source $symlink
+  else
+    echo "$source not a subdir of $BUILD_DIR"
+  fi
+done
 )
 
 if [ $? -eq 1 ]; then
-    echo "FAILED to stage ${APP_BASE} ${APP_DEPS}" | indent
-    exit 1
+  echo "FAILED to replace linked dependencies" | indent
+  exit 1
 fi
 
-echo "Copied ${APP_BASE} ${APP_DEPS} to application root successfully." | indent
+echo "Replaced linked dependencies successfully" | indent
